<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Wellnesscorner</name>
   <tag></tag>
   <elementGuidId>1f63bc9f-ff9d-47df-afb3-1549269f8d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af7c2228-a9c5-4271-b15f-4cdfac30d630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg</value>
      <webElementGuid>092329a0-f9ac-489d-b26d-79ceeae35eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;redirect-to-app-page template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;logo-header&quot;]/a[1]/img[1]</value>
      <webElementGuid>94e1c301-dc40-4344-81ce-1957cbf5b2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[2]/a/img</value>
      <webElementGuid>7c1beeee-0ec1-4794-9681-bb8c3f4e1e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg')]</value>
      <webElementGuid>89615f47-cad4-4695-b9e7-002c1eccfdd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b4ced682-7e16-46a3-acff-8bf1e2996a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/header/logo.svg']</value>
      <webElementGuid>83b55eda-6c63-4b1d-acb7-2d4b77bf55bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
