<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop_div_concat(6, , 9, ,  Feet)_ant-slider-handle ant-tooltip-open</name>
   <tag></tag>
   <elementGuidId>28b73584-4bae-446a-9da2-57f8fb8ca7d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-slider-handle.ant-tooltip-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d518648-d421-466a-b9da-1de388e4937a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-slider-handle ant-tooltip-open</value>
      <webElementGuid>2e52a449-3142-429a-89ae-4f511c0d5c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d59c294a-4b39-40f3-b3dc-ec6cd23c3227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>90cef30b-ac9c-45a0-9332-06ed65b55514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>761c4eab-4039-4db5-81c2-f7142a457dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>8a782630-c794-4201-945c-845384fc28aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>207</value>
      <webElementGuid>4687ea27-4411-4f6a-9bb6-7e8eda9137c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4e079f15-ba86-4c01-a9aa-f474d7399df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sm:tw-w-4/5 tw-w-full tw-m-auto tw-mb-12&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;tw-rounded-3xl tw-shadow-[0_2px_10px_#00000025] tw-bg-white md:tw-p-10 tw-px-6 tw-py-10&quot;]/div[@class=&quot;bmi-screen1&quot;]/div[@class=&quot;tw-mb-12&quot;]/div[@class=&quot;measure-wrapper tw-text-center tw-flex tw-justify-center tw-items-center tw-grid-flow-col&quot;]/div[@class=&quot;ant-row tw-w-full&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-slider ant-slider-horizontal&quot;]/div[@class=&quot;ant-slider-handle ant-tooltip-open&quot;]</value>
      <webElementGuid>f52d0ca2-bb51-4b9a-8a3f-413cabaff3f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>7d21c9fb-9ac5-4af9-9021-6bac1da2e0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>da5e79a7-d9f7-4b4b-a5c3-458080ea05d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
