<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter email to get started_fill round_ab306f</name>
   <tag></tag>
   <elementGuidId>ba7f44c2-b5ec-4413-8dd7-5230ac43ea82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='h']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.fill.roundedFormControl.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe56f2f4-2ea7-4771-860d-94171fb36450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a061a3cb-53cc-4fd3-81e7-01259a877a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a2da272e-fdcd-4c82-b6bb-06380c921bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>h</value>
      <webElementGuid>91a08523-cb82-468e-9a99-09d73bb83866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill roundedFormControl form-control</value>
      <webElementGuid>93622d30-eaa7-47b4-97cd-626a7de2fa57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-panel tw-pb-5&quot;]/div[@class=&quot;login-form tw-mb-2&quot;]/form[1]/div[@class=&quot;row-inner row&quot;]/div[@class=&quot;col&quot;]/input[@class=&quot;fill roundedFormControl form-control&quot;]</value>
      <webElementGuid>99e133ac-eb00-4afd-8c0b-be615c0bdabd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='h']</value>
      <webElementGuid>77e19f93-2f71-4448-bf42-d8137d7158cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/form/div/div/input</value>
      <webElementGuid>427315d7-ea45-41bf-b149-1a8a7e7087fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>13b2ade4-7d07-479b-a1d3-4d27f2e4ffcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>ce5aa9cc-5672-4876-ad39-3968dbc53611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
