<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>65769853-1bbc-4d70-abc7-00902d96b741</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div/div[9]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5733c0c-1f46-44ed-b04f-fc9e04baa49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg</value>
      <webElementGuid>3ccd5924-7475-4ab5-ad59-94ac64c30317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;user-dashboard md:tw-mt-0 tw-mt-7&quot;]/div[@class=&quot;md:tw-mb-10 feature-category-list md:tw-mt-5&quot;]/div[@class=&quot;ant-row feature-category-menu&quot;]/div[@class=&quot;ant-col ant-col-xs-8 ant-col-sm-6 ant-col-lg-4&quot;]/div[@class=&quot;feature-category-menu-item tw-relative md:hover:tw-shadow-[0_3px_14px_0_rgba(0,0,0,0.25)] md:hover:tw-rounded-2xl tw-transition tw-duration-300 hover:tw-transition-all hover:after:tw-content-[''] hover:after:tw-absolute hover:after:tw-bottom-0 hover:after:tw-h-1 hover:after:tw-left-0 hover:after:tw-right-0 hover:after:tw-m-auto hover:after:tw-w-3/12 hover:after:tw-bg-[#31C8C1] hover:after:tw-rounded-full&quot;]/a[1]/img[1]</value>
      <webElementGuid>e3b963e7-f616-4b86-a9d6-c563e158b529</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div[9]/div/a/img</value>
      <webElementGuid>e2b746d7-4273-4b36-8e4a-7e6bbc7e4d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg')]</value>
      <webElementGuid>48a7af77-9c37-4e95-b4e0-b11e12ebe6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a/img</value>
      <webElementGuid>c0160d70-53ac-4844-b07b-8fe09d6b888e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn-thewellnesscorner.s3.amazonaws.com/twc-web-images/dashboard/health-file.svg']</value>
      <webElementGuid>060b277e-c796-493e-81be-a8f8507911bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
