<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome_Password</name>
   <tag></tag>
   <elementGuidId>875f60cc-5226-4d10-b4a2-ead3f615eb36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fd0d9b1-83be-476d-859f-f816b42f7b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>972eefb5-03a3-4e0d-a07f-f989d6da4a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your password</value>
      <webElementGuid>6551d842-570c-4447-9d53-0b9a19416779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8e7ef9fa-6e47-4c61-ab69-5ff818916415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill roundedFormControl form-control</value>
      <webElementGuid>7e5bec04-c96a-4df8-8f1a-2f7161137ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-panel tw-pb-5&quot;]/div[@class=&quot;login-form&quot;]/form[1]/div[@class=&quot;row-inner row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-password&quot;]/input[@class=&quot;fill roundedFormControl form-control&quot;]</value>
      <webElementGuid>73e4dccf-e4ea-4e17-8641-35aa8cfb8adc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Password']</value>
      <webElementGuid>38ce964c-6d7e-4c82-b788-43100cc9a924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/form/div/div/div/input</value>
      <webElementGuid>fff9bbc5-2730-401c-bd57-4d92931f3434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4ae6f5c6-d87b-4f5f-b9dc-c38efa46bb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'Password' and @placeholder = 'Enter your password' and @type = 'password']</value>
      <webElementGuid>218e57bb-4735-4971-8a36-5db5e0b08791</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
