<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(5, , 0, ,  Feet)</name>
   <tag></tag>
   <elementGuidId>cf7d702f-7b12-4154-998d-ace685912ec3</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-slider-handle.ant-tooltip-open</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be2f2a08-6739-48a4-ab71-a44eae8058ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-slider-handle ant-tooltip-open</value>
      <webElementGuid>2d403fd9-4ad1-4a15-b81a-ffbc91ada22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>26866cb2-d217-497d-9d1f-1f079c463809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>381919d8-69d3-4f40-9621-17e8b4b928e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>5cbdeb39-8f0b-4fb2-abeb-31a54fb791d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>f45402d8-a395-43cc-a953-440227610b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>152</value>
      <webElementGuid>2da5b0f6-7aeb-418c-83c0-b9c896b00959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3769c594-35a8-4fd9-b93f-7cb7972cdb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sm:tw-w-4/5 tw-w-full tw-m-auto tw-mb-12&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;tw-rounded-3xl tw-shadow-[0_2px_10px_#00000025] tw-bg-white md:tw-p-10 tw-px-6 tw-py-10&quot;]/div[@class=&quot;bmi-screen1&quot;]/div[@class=&quot;tw-mb-12&quot;]/div[@class=&quot;measure-wrapper tw-text-center tw-flex tw-justify-center tw-items-center tw-grid-flow-col&quot;]/div[@class=&quot;ant-row tw-w-full&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-slider ant-slider-horizontal&quot;]/div[@class=&quot;ant-slider-handle ant-tooltip-open&quot;]</value>
      <webElementGuid>bc3a827d-072b-4840-943e-3f570d0c328a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>9a394b93-d2ad-4ac4-977e-63464b9756cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>0116e185-3456-49e9-a16e-a96e81648639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
