<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(6, , 1, ,  Feet)</name>
   <tag></tag>
   <elementGuidId>09f25a1d-3bc7-425e-8092-6177859bdc82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-slider-handle.ant-tooltip-open</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71275a33-6f73-4cb4-ac13-7983ec93f394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-slider-handle ant-tooltip-open</value>
      <webElementGuid>cf8fc133-1c8a-4fb3-b30d-e7efb2c14540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19977060-bf09-4fde-9952-181d29b3f70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>9fd9d59f-15f1-4487-b0dd-42c44baeca9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>fdd000f6-51d9-4846-9a6f-58649c61a7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>106c2c76-6e18-4227-8592-980f239f968c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>185</value>
      <webElementGuid>7ec52348-9411-49cc-9e43-8bec4583abad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>982fe64a-bcf5-4195-93b2-3e32354bc4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sm:tw-w-4/5 tw-w-full tw-m-auto tw-mb-12&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;tw-rounded-3xl tw-shadow-[0_2px_10px_#00000025] tw-bg-white md:tw-p-10 tw-px-6 tw-py-10&quot;]/div[@class=&quot;bmi-screen1&quot;]/div[@class=&quot;tw-mb-12&quot;]/div[@class=&quot;measure-wrapper tw-text-center tw-flex tw-justify-center tw-items-center tw-grid-flow-col&quot;]/div[@class=&quot;ant-row tw-w-full&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-slider ant-slider-horizontal&quot;]/div[@class=&quot;ant-slider-handle ant-tooltip-open&quot;]</value>
      <webElementGuid>7c6c1d8a-33c8-4d9a-aa95-50816bfd685f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>a2114332-6429-4f0a-b329-8d39bb46d7b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>f366af00-1700-4ca4-a908-03b27bb7e50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
