<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(5, , 0, ,  Feet)</name>
   <tag></tag>
   <elementGuidId>d96eb972-cc2d-4515-af97-838db83c92e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ant-slider-handle.ant-tooltip-open</value>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35cc9b34-bc57-4451-b2e5-96f3f65c1d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-slider-handle ant-tooltip-open</value>
      <webElementGuid>284fa66d-2391-4617-96b0-582b01d12994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ad388a4-99d7-496d-8dd6-814a9037c1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>c4d0259a-7baa-4dd2-b081-fdb0abf50791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>dbcbe09a-d2a6-44c7-b700-fc852fc8e79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemax</name>
      <type>Main</type>
      <value>220</value>
      <webElementGuid>a30abe5f-6743-4f12-beaf-59fe0f9a7147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>152</value>
      <webElementGuid>9d94b9c7-dc1c-4afa-a1c1-ae99787bfd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87fc4a40-66c0-4d3c-8845-27036ab5e011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;template&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;sm:tw-w-4/5 tw-w-full tw-m-auto tw-mb-12&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-xs-24 ant-col-lg-12&quot;]/div[@class=&quot;tw-rounded-3xl tw-shadow-[0_2px_10px_#00000025] tw-bg-white md:tw-p-10 tw-px-6 tw-py-10&quot;]/div[@class=&quot;bmi-screen1&quot;]/div[@class=&quot;tw-mb-12&quot;]/div[@class=&quot;measure-wrapper tw-text-center tw-flex tw-justify-center tw-items-center tw-grid-flow-col&quot;]/div[@class=&quot;ant-row tw-w-full&quot;]/div[@class=&quot;ant-col ant-col-24&quot;]/div[@class=&quot;ant-slider ant-slider-horizontal&quot;]/div[@class=&quot;ant-slider-handle ant-tooltip-open&quot;]</value>
      <webElementGuid>b3823434-1be1-4615-a83b-ec047c37c9c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/div/div/div/div[2]/div/div/div/div[4]</value>
      <webElementGuid>546a79a0-6808-4c3d-a483-4b68d69d3046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]</value>
      <webElementGuid>082a56d8-aa1e-498d-b813-777d1aca6404</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
