<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter email to get started_fill round_ab306f</name>
   <tag></tag>
   <elementGuidId>8c670338-e914-49af-a25f-4c488fb6034e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='r']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.fill.roundedFormControl.form-control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89d84b00-7f7c-4281-91f9-0d96e422bf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>97e269cb-a536-40ab-95bc-31adfda85d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>88e11925-3e63-4ba1-a43a-9de4fac7d396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>r</value>
      <webElementGuid>451c864d-45db-418f-893d-9512d1604711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fill roundedFormControl form-control</value>
      <webElementGuid>dc05caae-a8db-429c-a780-3f2ec1fc01ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;login&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;login-panel tw-pb-5&quot;]/div[@class=&quot;login-form tw-mb-2&quot;]/form[1]/div[@class=&quot;row-inner row&quot;]/div[@class=&quot;col&quot;]/input[@class=&quot;fill roundedFormControl form-control&quot;]</value>
      <webElementGuid>102bc57b-fd38-43ad-8421-779bd8879584</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='r']</value>
      <webElementGuid>85c90405-a9f0-4408-986f-7286ac6453a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/form/div/div/input</value>
      <webElementGuid>2d2da855-1936-4f41-8bc4-22b3b52420fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dcf43275-b64a-4203-886c-c31d384d82f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email']</value>
      <webElementGuid>71a15682-ef54-447e-967e-9ec6032f4c0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
